#!/bin/bash
# Calculate SMOL code coverage excluding GCOV_EXCL marked lines
#
# This script analyzes all .gcov files and provides accurate coverage metrics by:
# - Processing all C and H files (smol.c, smol_utils.c, smol_build.c, smol_scan.c, smol.h)
# - Excluding lines marked with GCOV_EXCL_LINE
# - Excluding code blocks between GCOV_EXCL_START and GCOV_EXCL_STOP
# - Treating GCOV_EXCL_LINE (flaky) specially: excluded but not reported as "excluded covered"
# - Reporting both excluded and measured line counts
# - Showing uncovered lines (optionally condensed into sections)
# - Showing excluded covered lines (candidates for removing GCOV_EXCL)
#
# Usage: ./calc_cov.sh [OPTIONS]
#   -c, --condensed              Show uncovered lines condensed into sections
#   -v, --verbose                Show all uncovered lines individually
#   -e, --show-excluded-covered  Show covered lines that are excluded (removable)
#   -h, --help                   Show this help message
#
# Default: Shows summary only (no line details)
# Requires: *.gcov files (generated by 'gcov *.c' after coverage test run)

MODE="summary"
SHOW_EXCLUDED_COVERED=0

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -c|--condensed)
            MODE="condensed"
            shift
            ;;
        -v|--verbose)
            MODE="verbose"
            shift
            ;;
        -e|--show-excluded-covered)
            SHOW_EXCLUDED_COVERED=1
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo "  -c, --condensed              Show uncovered lines condensed into sections"
            echo "  -v, --verbose                Show all uncovered lines individually"
            echo "  -e, --show-excluded-covered  Show covered lines that are excluded (removable)"
            echo "  -h, --help                   Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

# Find all .gcov files
# Note: In coverage builds, smol.h inline functions are moved to smol_h_coverage.c
#       so we exclude smol.h.gcov and include smol_h_coverage.c.gcov instead
if [ -f "smol_h_coverage.c.gcov" ]; then
    # Coverage build: include smol_h_coverage.c instead of smol.h
    GCOV_FILES=$(ls *.gcov 2>/dev/null | grep -E '^(smol|smol_utils|smol_build|smol_scan|smol_h_coverage)\.c\.gcov$')
else
    # Production build: include smol.h.gcov
    GCOV_FILES=$(ls *.gcov 2>/dev/null | grep -E '^(smol|smol_utils|smol_build|smol_scan)\.c\.gcov$|^smol\.h\.gcov$')
fi

if [ -z "$GCOV_FILES" ]; then
    echo "ERROR: No .gcov files found"
    echo "Run 'gcov *.c' after a coverage test run to generate them"
    exit 1
fi

echo "Processing files: $(echo $GCOV_FILES | tr '\n' ' ')"
echo ""

# First pass: Calculate coverage statistics across all files
awk '
BEGIN { excl_block = 0 }

# Track GCOV_EXCL_START/STOP blocks
/GCOV_EXCL_START/ { excl_block = 1; next }
/GCOV_EXCL_STOP/ { excl_block = 0; next }

# Line is excluded if: in excl_block OR has GCOV_EXCL_LINE
# But flaky lines (GCOV_EXCL_LINE (flaky)) are not counted as "excluded covered"
# SPECIAL CASE: In smol_h_coverage.c, ##### means "executed but count unavailable" (shared library limitation)
# so we treat it as COVERED instead of UNCOVERED
{
    is_excluded = (excl_block || /GCOV_EXCL_LINE/)
    is_flaky = /GCOV_EXCL_LINE.*\(flaky\)/
    is_uncovered_marker = /^ *#####:/
    is_covered_marker = /^ *[0-9]+\*?:/

    # Special handling for smol_h_coverage.c: ##### means covered (shared library issue)
    is_in_coverage_file = (FILENAME ~ /smol_h_coverage\.c\.gcov/)

    if (is_uncovered_marker) {
        if (is_in_coverage_file) {
            # In coverage file, ##### means executed but count unavailable -> treat as covered
            if (is_excluded) {
                excluded_cov++
            } else {
                covered++
            }
        } else {
            # In other files, ##### means truly uncovered
            if (is_excluded) {
                excluded_uncov++
            } else {
                uncovered++
            }
        }
    } else if (is_covered_marker) {
        if (is_excluded) {
            # Flaky lines are excluded but not counted as "excluded covered"
            if (!is_flaky) {
                excluded_cov++
            }
        } else {
            covered++
        }
    }
}

END {
    total_excluded = excluded_uncov + excluded_cov
    total_measured = uncovered + covered

    if (total_measured > 0) {
        pct = (covered * 100.0) / total_measured
    } else {
        pct = 0
    }

    printf "Coverage Report (excluding GCOV_EXCL):\n"
    printf "========================================\n"
    printf "Excluded lines: %d\n", total_excluded
    printf "  - Excluded uncovered: %d\n", excluded_uncov
    printf "  - Excluded covered: %d\n", excluded_cov
    printf "Measured lines: %d\n", total_measured
    printf "  - Covered: %d\n", covered
    printf "  - Uncovered: %d\n", uncovered
    printf "Coverage: %.2f%%\n", pct
}
' $GCOV_FILES

# If verbose or condensed mode, show uncovered lines
if [ "$MODE" = "verbose" ] || [ "$MODE" = "condensed" ]; then
    echo ""
    echo "========================================"

    if [ "$MODE" = "verbose" ]; then
        echo "Uncovered Lines (detailed):"
        echo "========================================"

        # Show all uncovered lines with code, including filename
        awk '
        BEGIN { excl_block = 0 }

        /GCOV_EXCL_START/ { excl_block = 1; next }
        /GCOV_EXCL_STOP/ { excl_block = 0; next }

        /^ *#####:/ && !excl_block && !/GCOV_EXCL_LINE/ {
            # Skip smol_h_coverage.c - ##### means covered there (shared library limitation)
            if (FILENAME ~ /smol_h_coverage\.c\.gcov/) next

            # Extract filename from FILENAME (e.g., smol.c.gcov -> smol.c)
            fname = FILENAME
            sub(/\.gcov$/, "", fname)

            # Extract line number (field after #####:)
            line = $0
            sub(/^ *#####: */, "", line)
            split(line, parts, ":")
            line_num = parts[1] + 0  # Force numeric conversion
            # Extract code (everything after first :)
            sub(/^[0-9]+:/, "", line)
            code = line
            # Trim leading/trailing whitespace from code
            gsub(/^[ \t]+/, "", code)
            gsub(/[ \t]+$/, "", code)
            printf "  %s:%d: %s\n", fname, line_num, code
        }
        ' $GCOV_FILES

    elif [ "$MODE" = "condensed" ]; then
        echo "Uncovered Lines (condensed by section):"
        echo "========================================"

        # Show uncovered lines grouped into consecutive sections per file
        awk '
        BEGIN {
            excl_block = 0
            in_section = 0
            section_start = 0
            section_end = 0
            prev_line = 0
            prev_file = ""
        }

        /GCOV_EXCL_START/ { excl_block = 1; next }
        /GCOV_EXCL_STOP/ { excl_block = 0; next }

        /^ *#####:/ && !excl_block && !/GCOV_EXCL_LINE/ {
            # Skip smol_h_coverage.c - ##### means covered there (shared library limitation)
            if (FILENAME ~ /smol_h_coverage\.c\.gcov/) next

            # Extract filename from FILENAME (e.g., smol.c.gcov -> smol.c)
            fname = FILENAME
            sub(/\.gcov$/, "", fname)

            # Extract line number and code (portable method)
            line = $0
            sub(/^ *#####: */, "", line)
            split(line, parts, ":")
            line_num = parts[1] + 0  # Force numeric conversion
            # Get code after first colon
            sub(/^[0-9]+:/, "", line)
            code = line
            # Trim leading/trailing whitespace from code
            gsub(/^[ \t]+/, "", code)
            gsub(/[ \t]+$/, "", code)

            # Check if we switched to a new file
            if (fname != prev_file) {
                # Print previous section if any
                if (in_section) {
                    if (section_start == section_end) {
                        printf "  %s:%d: %s\n", prev_file, section_start, section_code
                    } else {
                        printf "  %s:%d-%d: %s ... (%d lines)\n", prev_file, section_start, section_end, section_code, (section_end - section_start + 1)
                    }
                }
                # Start new section in new file
                section_start = line_num
                section_end = line_num
                section_code = code
                in_section = 1
                prev_file = fname
            } else if (!in_section) {
                # Start new section in same file
                section_start = line_num
                section_end = line_num
                section_code = code
                in_section = 1
            } else if (line_num == prev_line + 1) {
                # Continue current section
                section_end = line_num
            } else {
                # Print previous section and start new one
                if (section_start == section_end) {
                    printf "  %s:%d: %s\n", prev_file, section_start, section_code
                } else {
                    printf "  %s:%d-%d: %s ... (%d lines)\n", prev_file, section_start, section_end, section_code, (section_end - section_start + 1)
                }

                # Start new section
                section_start = line_num
                section_end = line_num
                section_code = code
            }

            prev_line = line_num
            prev_file = fname
        }

        END {
            # Print last section if any
            if (in_section) {
                if (section_start == section_end) {
                    printf "  %s:%d: %s\n", prev_file, section_start, section_code
                } else {
                    printf "  %s:%d-%d: %s ... (%d lines)\n", prev_file, section_start, section_end, section_code, (section_end - section_start + 1)
                }
            }
        }
        ' $GCOV_FILES
    fi
fi

# Show excluded covered lines if requested
if [ "$SHOW_EXCLUDED_COVERED" -eq 1 ]; then
    echo ""
    echo "========================================"
    echo "Excluded Covered Lines (removable GCOV_EXCL):"
    echo "========================================"
    echo "These lines are covered by tests but marked with GCOV_EXCL."
    echo "Consider removing GCOV_EXCL markers to include them in coverage."
    echo ""

    awk '
    BEGIN { excl_block = 0; count = 0 }

    /GCOV_EXCL_START/ { excl_block = 1; next }
    /GCOV_EXCL_STOP/ { excl_block = 0; next }

    /^ *[0-9]+\*?:/ && (excl_block || /GCOV_EXCL_LINE/) {
        # Skip flaky lines - they are intentionally excluded and should not be reported
        if (/GCOV_EXCL_LINE.*\(flaky\)/) {
            next
        }

        # Extract filename from FILENAME (e.g., smol.c.gcov -> smol.c)
        fname = FILENAME
        sub(/\.gcov$/, "", fname)

        # This is a covered line that is excluded
        line = $0
        sub(/^ *[0-9]+\*?: */, "", line)
        split(line, parts, ":")
        line_num = parts[1] + 0  # Force numeric conversion
        # Get code after first colon
        sub(/^[0-9]+:/, "", line)
        code = line
        # Trim leading/trailing whitespace
        gsub(/^[ \t]+/, "", code)
        gsub(/[ \t]+$/, "", code)

        # Show marker type
        marker = ""
        if (/GCOV_EXCL_LINE/) {
            marker = " [GCOV_EXCL_LINE]"
        } else if (excl_block) {
            marker = " [in GCOV_EXCL_START/STOP block]"
        }

        printf "  %s:%d%s: %s\n", fname, line_num, marker, code
        count++
    }

    END {
        if (count == 0) {
            print "  (none found - all excluded lines are uncovered)"
        } else {
            printf "\nTotal: %d covered lines marked as excluded\n", count
        }
    }
    ' $GCOV_FILES
fi

echo ""

# Explicit success exit to ensure script returns 0 when coverage calculation succeeds
exit 0
